require("dotenv").config();
const express = require("express");
const session = require("express-session");
const bcrypt = require("bcryptjs");
const Database = require("better-sqlite3");
const multer = require("multer");
const path = require("path");
const fs = require("fs");
const crypto = require("crypto");
const helmet = require("helmet");
const rateLimit = require("express-rate-limit");
const nodemailer = require("nodemailer");

class SQLiteSessionStore extends session.Store {
  constructor(client) { super(); this.client = client; this.client.exec("CREATE TABLE IF NOT EXISTS sessions(sid TEXT PRIMARY KEY,sess TEXT NOT NULL,expire INTEGER NOT NULL)"); this.client.prepare("DELETE FROM sessions WHERE expire<=?").run(Date.now()) }
  get(sid, cb) { try { const row = this.client.prepare("SELECT sess,expire FROM sessions WHERE sid=?").get(sid); if (!row || row.expire <= Date.now()) { if (row) this.destroy(sid, () => { }); return cb(null, null) } cb(null, JSON.parse(row.sess)) } catch (e) { cb(e) } }
  set(sid, sess, cb) { try { const expire = sess.cookie && sess.cookie.expires ? new Date(sess.cookie.expires).getTime() : Date.now() + 1000 * 60 * 60 * 8; this.client.prepare("INSERT INTO sessions(sid,sess,expire) VALUES(?,?,?) ON CONFLICT(sid) DO UPDATE SET sess=excluded.sess,expire=excluded.expire").run(sid, JSON.stringify(sess), expire); cb && cb(null) } catch (e) { cb && cb(e) } }
  touch(sid, sess, cb) { try { const expire = sess.cookie && sess.cookie.expires ? new Date(sess.cookie.expires).getTime() : Date.now() + 1000 * 60 * 60 * 8; this.client.prepare("UPDATE sessions SET expire=? WHERE sid=?").run(expire, sid); cb && cb(null) } catch (e) { cb && cb(e) } }
  destroy(sid, cb) { try { this.client.prepare("DELETE FROM sessions WHERE sid=?").run(sid); cb && cb(null) } catch (e) { cb && cb(e) } }
  clear(cb) { try { this.client.prepare("DELETE FROM sessions").run(); cb && cb(null) } catch (e) { cb && cb(e) } }
  length(cb) { try { cb(null, this.client.prepare("SELECT COUNT(*) c FROM sessions").get().c) } catch (e) { cb(e) } }
  all(cb) { try { const rows = this.client.prepare("SELECT sess FROM sessions WHERE expire>? ").all(Date.now()).map(x => JSON.parse(x.sess)); cb(null, rows) } catch (e) { cb(e) } }
}
const app = express();
const PORT = Number(process.env.PORT || 3000);
const isProd = process.env.NODE_ENV === "production";

if (isProd) {
  if (!process.env.SESSION_SECRET || process.env.SESSION_SECRET.length < 32) throw new Error("SESSION_SECRET deve ter pelo menos 32 caracteres em produção.");
  if (!process.env.ADMIN_EMAIL || !process.env.ADMIN_PASSWORD || process.env.ADMIN_PASSWORD.length < 10) throw new Error("ADMIN_EMAIL e ADMIN_PASSWORD fortes são obrigatórios em produção.");
  if (!process.env.APP_URL || !/^https:\/\//i.test(process.env.APP_URL)) throw new Error("APP_URL deve ser uma URL HTTPS em produção.");
  app.set("trust proxy", 1);
}
const dbPath = process.env.DB_PATH || path.join(__dirname, "imobpro.sqlite");
const db = new Database(dbPath);
db.pragma("journal_mode=WAL"); db.pragma("foreign_keys=ON");
const uploadDir = path.join(__dirname, "uploads"); fs.mkdirSync(uploadDir, { recursive: true });
app.disable("x-powered-by");
app.use(helmet({ contentSecurityPolicy: false, referrerPolicy: { policy: "strict-origin-when-cross-origin" } }));
app.use((req, res, next) => { res.setHeader("X-Content-Type-Options", "nosniff"); res.setHeader("X-Frame-Options", "DENY"); if (req.path.startsWith("/api/")) res.setHeader("Cache-Control", "no-store"); next() });
app.use(express.json({ limit: "3mb" })); app.use(express.urlencoded({ extended: true, limit: "3mb" }));
app.use(express.static(path.join(__dirname, "public"))); app.use("/uploads", express.static(uploadDir));
app.use(session({ name: isProd ? "__Host-imob.sid" : "imob.sid", secret: process.env.SESSION_SECRET || "dev-secret-change-me", resave: false, saveUninitialized: false, store: new SQLiteSessionStore(db), rolling: true, cookie: { httpOnly: true, sameSite: "lax", secure: isProd, maxAge: 1000 * 60 * 60 * 8, path: "/" } }));
const authLimiter = rateLimit({ windowMs: 15 * 60 * 1000, max: 25, standardHeaders: true, legacyHeaders: false, message: { error: "Muitas tentativas. Aguarde alguns minutos e tente novamente." } });
app.use(["/api/auth/login", "/api/auth/register", "/api/auth/forgot-password", "/api/auth/reset-password"], authLimiter);

app.get("/api/health", (req, res) => res.json({ ok: true, service: "imob-pro", environment: isProd ? "production" : "development", time: new Date().toISOString() }));

db.exec(`
CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'customer',phone TEXT DEFAULT '',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS properties(id INTEGER PRIMARY KEY AUTOINCREMENT,owner_id INTEGER,title TEXT NOT NULL,type TEXT NOT NULL,purpose TEXT NOT NULL,price REAL NOT NULL DEFAULT 0,city TEXT NOT NULL,neighborhood TEXT NOT NULL,address TEXT DEFAULT '',area REAL DEFAULT 0,bedrooms INTEGER DEFAULT 0,suites INTEGER DEFAULT 0,bathrooms INTEGER DEFAULT 0,parking INTEGER DEFAULT 0,condo REAL DEFAULT 0,iptu REAL DEFAULT 0,description TEXT DEFAULT '',features TEXT DEFAULT '',status TEXT NOT NULL DEFAULT 'draft',cover_image TEXT,video_url TEXT DEFAULT '',latitude REAL,longitude REAL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(owner_id) REFERENCES users(id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS property_images(id INTEGER PRIMARY KEY AUTOINCREMENT,property_id INTEGER NOT NULL,filename TEXT NOT NULL,sort_order INTEGER DEFAULT 0,FOREIGN KEY(property_id) REFERENCES properties(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS leads(id INTEGER PRIMARY KEY AUTOINCREMENT,customer_id INTEGER,name TEXT NOT NULL,whatsapp TEXT NOT NULL,email TEXT DEFAULT '',property_id INTEGER,message TEXT DEFAULT '',status TEXT NOT NULL DEFAULT 'new',source TEXT DEFAULT 'site',assigned_to INTEGER,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(customer_id) REFERENCES users(id) ON DELETE SET NULL,FOREIGN KEY(property_id) REFERENCES properties(id) ON DELETE SET NULL,FOREIGN KEY(assigned_to) REFERENCES users(id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS visits(id INTEGER PRIMARY KEY AUTOINCREMENT,lead_id INTEGER,property_id INTEGER,customer_id INTEGER,agent_id INTEGER,visit_date TEXT NOT NULL,notes TEXT DEFAULT '',status TEXT DEFAULT 'scheduled',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(lead_id) REFERENCES leads(id) ON DELETE SET NULL,FOREIGN KEY(property_id) REFERENCES properties(id) ON DELETE SET NULL,FOREIGN KEY(customer_id) REFERENCES users(id) ON DELETE SET NULL,FOREIGN KEY(agent_id) REFERENCES users(id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS favorites(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,property_id INTEGER NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(user_id,property_id),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(property_id) REFERENCES properties(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS saved_searches(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,name TEXT NOT NULL,filters_json TEXT NOT NULL,frequency TEXT DEFAULT 'instant',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS collections(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,name TEXT NOT NULL,description TEXT DEFAULT '',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS collection_items(id INTEGER PRIMARY KEY AUTOINCREMENT,collection_id INTEGER NOT NULL,property_id INTEGER NOT NULL,comment TEXT DEFAULT '',UNIQUE(collection_id,property_id),FOREIGN KEY(collection_id) REFERENCES collections(id) ON DELETE CASCADE,FOREIGN KEY(property_id) REFERENCES properties(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS tasks(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,lead_id INTEGER,property_id INTEGER,title TEXT NOT NULL,due_at TEXT,priority TEXT DEFAULT 'normal',status TEXT DEFAULT 'open',notes TEXT DEFAULT '',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL,FOREIGN KEY(lead_id) REFERENCES leads(id) ON DELETE SET NULL,FOREIGN KEY(property_id) REFERENCES properties(id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS notifications(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,title TEXT NOT NULL,message TEXT NOT NULL,type TEXT DEFAULT 'info',read_at TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS activity_log(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,entity_type TEXT,entity_id INTEGER,action TEXT,details TEXT DEFAULT '',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS password_reset_tokens(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,token_hash TEXT UNIQUE NOT NULL,expires_at TEXT NOT NULL,used_at TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS property_views(id INTEGER PRIMARY KEY AUTOINCREMENT,property_id INTEGER NOT NULL,user_id INTEGER,session_key TEXT,source TEXT DEFAULT 'direct',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(property_id) REFERENCES properties(id) ON DELETE CASCADE,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS saved_search_alerts(id INTEGER PRIMARY KEY AUTOINCREMENT,search_id INTEGER NOT NULL,last_sent_at TEXT,FOREIGN KEY(search_id) REFERENCES saved_searches(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS messages(id INTEGER PRIMARY KEY AUTOINCREMENT,sender_id INTEGER,recipient_id INTEGER,property_id INTEGER,lead_id INTEGER,body TEXT NOT NULL,read_at TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(sender_id) REFERENCES users(id) ON DELETE SET NULL,FOREIGN KEY(recipient_id) REFERENCES users(id) ON DELETE SET NULL,FOREIGN KEY(property_id) REFERENCES properties(id) ON DELETE SET NULL,FOREIGN KEY(lead_id) REFERENCES leads(id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS site_pages(id INTEGER PRIMARY KEY AUTOINCREMENT,slug TEXT UNIQUE NOT NULL,title TEXT NOT NULL,content TEXT DEFAULT '',published INTEGER DEFAULT 1,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS privacy_requests(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,type TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'open',details TEXT DEFAULT '',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS automation_rules(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,trigger_key TEXT NOT NULL,enabled INTEGER NOT NULL DEFAULT 1,action_key TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
`);
function seed() {
  const adminEmail = (process.env.ADMIN_EMAIL || "admin@imobpro.local").toLowerCase();
  if (!db.prepare("SELECT id FROM users WHERE lower(email)=lower(?)").get(adminEmail)) db.prepare("INSERT INTO users(name,email,password_hash,role) VALUES(?,?,?,?)").run("Administrador", adminEmail, bcrypt.hashSync(process.env.ADMIN_PASSWORD || "admin123", 12), "admin");
  if (db.prepare("SELECT COUNT(*) c FROM properties").get().c === 0) {
    const admin = db.prepare("SELECT id FROM users WHERE role='admin' ORDER BY id LIMIT 1").get(); const s = db.prepare("INSERT INTO properties(owner_id,title,type,purpose,price,city,neighborhood,address,area,bedrooms,suites,bathrooms,parking,condo,iptu,description,features,status,cover_image) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
    s.run(admin.id, "Apartamento sofisticado no Meireles", "Apartamento", "venda", 895000, "Fortaleza", "Meireles", "Av. Beira-Mar, 000", 118, 3, 2, 3, 2, 980, 2400, "Apartamento amplo, iluminado e pronto para morar, com ambientes integrados e excelente localização.", "Varanda|Ar-condicionado|Elevador|Piscina|Academia|Portaria|Mobiliado", "published", "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1400&q=85");
    s.run(admin.id, "Casa contemporânea com piscina", "Casa", "venda", 1250000, "Fortaleza", "Cocó", "Rua Exemplo, 000", 260, 4, 3, 5, 4, 0, 0, "Casa contemporânea com área externa, piscina e espaços amplos para a família.", "Piscina|Jardim|Churrasqueira|Ar-condicionado|Closet|Área gourmet", "published", "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1400&q=85");
    s.run(admin.id, "Apartamento para alugar na Aldeota", "Apartamento", "aluguel", 3200, "Fortaleza", "Aldeota", "Rua Exemplo, 000", 82, 2, 1, 2, 1, 650, 0, "Apartamento funcional em região valorizada, com boa mobilidade e serviços próximos.", "Elevador|Portaria|Varanda|Academia|Pet friendly", "published", "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1400&q=85");
  }
  const defs = { company_name: "Imob Pro", whatsapp: "5585999999999", phone: "(85) 99999-9999", email: "contato@imobpro.local", city: "Fortaleza - CE", primary_color: "#B08D57", hero_title: "Encontre o lugar onde sua próxima história começa.", hero_subtitle: "Uma experiência imobiliária completa para comprar, alugar e anunciar.", instagram: "", facebook: "", linkedin: "" }; const st = db.prepare("INSERT OR IGNORE INTO settings(key,value) VALUES(?,?)"); Object.entries(defs).forEach(([k, v]) => st.run(k, v));
} seed();
const storage = multer.diskStorage({ destination: uploadDir, filename: (_, f, cb) => cb(null, crypto.randomUUID() + path.extname(f.originalname).toLowerCase()) });
const upload = multer({ storage, limits: { fileSize: 10 * 1024 * 1024 }, fileFilter: (_, f, cb) => cb(/image\/(jpeg|png|webp|jpg)/.test(f.mimetype) ? null : new Error("Apenas JPG, PNG ou WEBP.")) });
const roles = { admin: ["admin", "manager", "editor", "agent", "owner", "customer"], manager: ["manager", "editor", "agent", "owner", "customer"], editor: ["editor"], agent: ["agent", "customer"], owner: ["owner"], customer: ["customer"] };
function auth(req, res, next) { if (!req.session.user) return res.status(401).json({ error: "Não autenticado." }); next() }
function staff(req, res, next) { if (!req.session.user || !["admin", "manager", "editor", "agent"].includes(req.session.user.role)) return res.status(403).json({ error: "Acesso negado." }); next() }
function manage(req, res, next) { if (!req.session.user || !["admin", "manager", "editor"].includes(req.session.user.role)) return res.status(403).json({ error: "Acesso negado." }); next() }
function agentOnly(req, res, next) { if (!req.session.user || req.session.user.role !== "agent") return res.status(403).json({ error: "Acesso restrito aos atendentes." }); next() }
function getSettings() { return Object.fromEntries(db.prepare("SELECT key,value FROM settings").all().map(x => [x.key, x.value])) }
function publicUser(u) { return u && { id: u.id, name: u.name, email: u.email, role: u.role, phone: u.phone || "" } }
function normalize(p) { if (!p) return null; p.features = p.features ? p.features.split("|").filter(Boolean) : []; p.images = db.prepare("SELECT id,filename,sort_order FROM property_images WHERE property_id=? ORDER BY sort_order,id").all(p.id); if (p.cover_image && !/^https?:\/\//.test(p.cover_image)) p.cover_image = "/uploads/" + p.cover_image; return p }
function log(req, action, type, id, details = "") { db.prepare("INSERT INTO activity_log(user_id,entity_type,entity_id,action,details) VALUES(?,?,?,?,?)").run(req.session.user?.id || null, type, id, action, details) }
function notify(userId, title, message, type = "info") { if (userId) db.prepare("INSERT INTO notifications(user_id,title,message,type) VALUES(?,?,?,?)").run(userId, title, message, type) }
const mailer = process.env.SMTP_HOST ? nodemailer.createTransport({ host: process.env.SMTP_HOST, port: Number(process.env.SMTP_PORT || 587), secure: String(process.env.SMTP_SECURE) === "true", auth: process.env.SMTP_USER ? { user: process.env.SMTP_USER, pass: process.env.SMTP_PASS } : undefined }) : null;
async function sendMail(to, subject, text) { if (!mailer || !to) return false; try { await mailer.sendMail({ from: process.env.MAIL_FROM || process.env.SMTP_USER, to, subject, text }); return true } catch (e) { console.error("E-mail não enviado:", e.message); return false } }
function propertyPayload(b, p = {}) { return [b.title ?? p.title, b.type ?? p.type, b.purpose ?? p.purpose, Number(b.price ?? p.price) || 0, b.city ?? p.city, b.neighborhood ?? p.neighborhood, b.address ?? p.address ?? "", Number(b.area ?? p.area) || 0, Number(b.bedrooms ?? p.bedrooms) || 0, Number(b.suites ?? p.suites) || 0, Number(b.bathrooms ?? p.bathrooms) || 0, Number(b.parking ?? p.parking) || 0, Number(b.condo ?? p.condo) || 0, Number(b.iptu ?? p.iptu) || 0, b.description ?? p.description ?? "", Array.isArray(b.features) ? b.features.join("|") : (b.features ?? p.features ?? ""), b.video_url ?? p.video_url ?? "", b.latitude ?? p.latitude ?? null, b.longitude ?? p.longitude ?? null] }

app.get("/api/settings", (_, res) => res.json(getSettings()));
app.get("/api/auth/me", (req, res) => res.json(req.session.user || null));
app.post("/api/auth/login", (req, res) => {
  const email = String(req.body.email || "").trim().toLowerCase(); const password = String(req.body.password || ""); let u = db.prepare("SELECT * FROM users WHERE lower(email)=?").get(email);
  // Em desenvolvimento, as credenciais administrativas definidas no .env também funcionam
  // para recuperar um banco local antigo sem apagar usuários, imóveis ou leads.
  const recoveryPassword = process.env.ADMIN_PASSWORD || (!isProd ? "admin123" : "");
  if (u && !bcrypt.compareSync(password, u.password_hash) && u.role === "admin" && recoveryPassword && password === recoveryPassword && (!isProd || process.env.ADMIN_SYNC_PASSWORD === "true")) {
    db.prepare("UPDATE users SET password_hash=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(bcrypt.hashSync(password, 12), u.id);
    u = db.prepare("SELECT * FROM users WHERE id=?").get(u.id);
  }
  if (!u || !bcrypt.compareSync(password, u.password_hash)) return res.status(401).json({ error: "E-mail ou senha inválidos." });
  req.session.regenerate(err => { if (err) return res.status(500).json({ error: "Não foi possível iniciar a sessão." }); req.session.user = publicUser(u); log(req, "login", "user", u.id); res.json(req.session.user) })
});
app.post("/api/auth/register", (req, res) => { const { name, email, password, phone = "" } = req.body || {}; if (!name || !email || !password || password.length < 8) return res.status(400).json({ error: "Nome, e-mail e senha de pelo menos 8 caracteres são obrigatórios." }); try { const r = db.prepare("INSERT INTO users(name,email,password_hash,role,phone) VALUES(?,?,?,?,?)").run(name.trim(), email.trim().toLowerCase(), bcrypt.hashSync(password, 12), "customer", phone); const u = db.prepare("SELECT * FROM users WHERE id=?").get(r.lastInsertRowid); req.session.regenerate(err => { if (err) return res.status(500).json({ error: "Não foi possível iniciar a sessão." }); req.session.user = publicUser(u); res.status(201).json(req.session.user) }) } catch (e) { res.status(409).json({ error: "Este e-mail já está cadastrado." }) } });
app.post("/api/auth/logout", (req, res) => req.session.destroy(() => res.json({ ok: true })));
app.post("/api/auth/admin-recover", (req, res) => {
  if (isProd && process.env.ADMIN_RECOVERY_ENABLED !== "true") return res.status(404).json({ error: "Rota não disponível." });
  const email = String(req.body.email || "").trim().toLowerCase();
  const password = String(req.body.password || "");
  const recoveryKey = String(req.body.recoveryKey || "");
  const expectedKey = process.env.ADMIN_RECOVERY_KEY || (!isProd ? "imobpro-local-recovery" : "");
  if (!email || password.length < 10 || !expectedKey || recoveryKey !== expectedKey) return res.status(403).json({ error: "Dados de recuperação inválidos." });
  const u = db.prepare("SELECT * FROM users WHERE lower(email)=? AND role='admin'").get(email);
  if (!u) return res.status(404).json({ error: "Administrador não encontrado." });
  db.prepare("UPDATE users SET password_hash=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(bcrypt.hashSync(password, 12), u.id);
  db.prepare("DELETE FROM sessions").run();
  res.json({ ok: true, message: "Senha administrativa redefinida. Faça login novamente." });
});

app.post("/api/auth/change-password", auth, (req, res) => { const { currentPassword, newPassword } = req.body || {}; const u = db.prepare("SELECT * FROM users WHERE id=?").get(req.session.user.id); if (!bcrypt.compareSync(currentPassword || "", u.password_hash)) return res.status(400).json({ error: "Senha atual incorreta." }); if (!newPassword || newPassword.length < 6) return res.status(400).json({ error: "A nova senha precisa ter pelo menos 6 caracteres." }); db.prepare("UPDATE users SET password_hash=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(bcrypt.hashSync(newPassword, 12), u.id); log(req, "change_password", "user", u.id); res.json({ ok: true }) });
app.post("/api/auth/forgot-password", (req, res) => { const email = String(req.body.email || "").trim().toLowerCase(); const u = db.prepare("SELECT id FROM users WHERE lower(email)=?").get(email); let devToken = null; if (u) { db.prepare("UPDATE password_reset_tokens SET used_at=CURRENT_TIMESTAMP WHERE user_id=? AND used_at IS NULL").run(u.id); const raw = crypto.randomBytes(32).toString("hex"); db.prepare("INSERT INTO password_reset_tokens(user_id,token_hash,expires_at) VALUES(?,?,?)").run(u.id, crypto.createHash("sha256").update(raw).digest("hex"), new Date(Date.now() + 30 * 60 * 1000).toISOString()); devToken = raw; } const payload = { ok: true, message: "Se o e-mail existir, um link de recuperação foi preparado." }; if (u && mailer) { const link = `${process.env.APP_URL || `http://localhost:${PORT}`}/?reset=${devToken}`; sendMail(email, "Redefinição de senha — Imob Pro", `Use este código para redefinir sua senha: ${devToken}\n\nLink: ${link}\n\nO código expira em 30 minutos.`) } if (process.env.NODE_ENV !== "production" && devToken) payload.devToken = devToken; res.json(payload) });
app.post("/api/auth/reset-password", (req, res) => { const token = String(req.body.token || ""); const password = String(req.body.password || ""); if (token.length < 20 || password.length < 8) return res.status(400).json({ error: "Token inválido ou senha muito curta." }); const hash = crypto.createHash("sha256").update(token).digest("hex"); const row = db.prepare("SELECT * FROM password_reset_tokens WHERE token_hash=? AND used_at IS NULL AND expires_at>? ").get(hash, new Date().toISOString()); if (!row) return res.status(400).json({ error: "Token inválido ou expirado." }); db.prepare("UPDATE users SET password_hash=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(bcrypt.hashSync(password, 12), row.user_id); db.prepare("UPDATE password_reset_tokens SET used_at=CURRENT_TIMESTAMP WHERE id=?").run(row.id); res.json({ ok: true, message: "Senha redefinida com sucesso." }) });

app.get("/api/properties", (req, res) => { const q = req.query; let sql = "SELECT p.*,u.name owner_name FROM properties p LEFT JOIN users u ON u.id=p.owner_id WHERE 1=1", a = []; const privileged = req.session.user && ["admin", "manager", "editor", "agent"].includes(req.session.user.role); if (!privileged) sql += " AND p.status='published'"; if (q.status) { sql += " AND p.status=?"; a.push(q.status) } if (q.purpose) { sql += " AND p.purpose=?"; a.push(q.purpose) } if (q.type) { sql += " AND p.type=?"; a.push(q.type) } if (q.city) { sql += " AND lower(p.city) LIKE lower(?)"; a.push("%" + q.city + "%") } if (q.neighborhood) { sql += " AND lower(p.neighborhood) LIKE lower(?)"; a.push("%" + q.neighborhood + "%") } if (q.minPrice) { sql += " AND p.price>=?"; a.push(Number(q.minPrice)) } if (q.maxPrice) { sql += " AND p.price<=?"; a.push(Number(q.maxPrice)) } if (q.bedrooms) { sql += " AND p.bedrooms>=?"; a.push(Number(q.bedrooms)) } if (q.parking) { sql += " AND p.parking>=?"; a.push(Number(q.parking)) } if (q.q) { sql += " AND (lower(p.title) LIKE lower(?) OR lower(p.neighborhood) LIKE lower(?) OR lower(p.city) LIKE lower(?))"; const s = "%" + q.q + "%"; a.push(s, s, s) } sql += " ORDER BY p.updated_at DESC LIMIT 100"; res.json(db.prepare(sql).all(...a).map(normalize)) });
app.get("/api/properties/:id", (req, res) => { const p = normalize(db.prepare("SELECT p.*,u.name owner_name FROM properties p LEFT JOIN users u ON u.id=p.owner_id WHERE p.id=?").get(req.params.id)); if (!p) return res.status(404).json({ error: "Imóvel não encontrado." }); if (p.status !== "published" && !req.session.user) return res.status(404).json({ error: "Imóvel não encontrado." }); res.json(p) });
app.post("/api/leads", (req, res) => { const b = req.body || {}; if (!b.name || !b.whatsapp) return res.status(400).json({ error: "Nome e WhatsApp são obrigatórios." }); let customerId = req.session.user?.role === "customer" ? req.session.user.id : null; if (!customerId && b.email) { const existing = db.prepare("SELECT id FROM users WHERE lower(email)=lower(?)").get(b.email); customerId = existing?.id || null } const r = db.prepare("INSERT INTO leads(customer_id,name,whatsapp,email,property_id,message,source) VALUES(?,?,?,?,?,?,?)").run(customerId, b.name, b.whatsapp, b.email || "", b.property_id || null, b.message || "", b.source || "site"); const agents = db.prepare("SELECT id FROM users WHERE role='agent' ORDER BY id").all(); if (agents.length) { const cursor = Number(db.prepare("SELECT value FROM settings WHERE key='lead_rr_cursor'").get()?.value || 0); const agent = agents[cursor % agents.length]; db.prepare("INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").run("lead_rr_cursor", String(cursor + 1)); db.prepare("UPDATE leads SET assigned_to=? WHERE id=?").run(agent.id, r.lastInsertRowid); notify(agent.id, "Novo lead", "Um novo cliente demonstrou interesse.", "lead"); db.prepare("INSERT INTO tasks(user_id,lead_id,title,priority) VALUES(?,?,?,?)").run(agent.id, r.lastInsertRowid, "Fazer primeiro contato com novo lead", "high"); } res.status(201).json({ id: r.lastInsertRowid }) });

app.get("/api/me/favorites", auth, (req, res) => res.json(db.prepare("SELECT p.* FROM favorites f JOIN properties p ON p.id=f.property_id WHERE f.user_id=? ORDER BY f.created_at DESC").all(req.session.user.id).map(normalize)));
app.post("/api/me/favorites/:propertyId", auth, (req, res) => { try { db.prepare("INSERT INTO favorites(user_id,property_id) VALUES(?,?)").run(req.session.user.id, req.params.propertyId) } catch { } res.json({ ok: true }) });
app.delete("/api/me/favorites/:propertyId", auth, (req, res) => { db.prepare("DELETE FROM favorites WHERE user_id=? AND property_id=?").run(req.session.user.id, req.params.propertyId); res.json({ ok: true }) });
app.get("/api/me/collections", auth, (req, res) => res.json(db.prepare("SELECT * FROM collections WHERE user_id=? ORDER BY created_at DESC").all(req.session.user.id).map(c => ({ ...c, items: db.prepare("SELECT p.*,ci.comment FROM collection_items ci JOIN properties p ON p.id=ci.property_id WHERE ci.collection_id=?").all(c.id).map(normalize) }))));
app.post("/api/me/collections", auth, (req, res) => { const name = String(req.body.name || "").trim(); if (!name) return res.status(400).json({ error: "Nome da coleção obrigatório." }); const r = db.prepare("INSERT INTO collections(user_id,name,description) VALUES(?,?,?)").run(req.session.user.id, name, req.body.description || ""); res.status(201).json({ id: r.lastInsertRowid }) });
app.post("/api/me/collections/:id/items", auth, (req, res) => { const c = db.prepare("SELECT id FROM collections WHERE id=? AND user_id=?").get(req.params.id, req.session.user.id); if (!c) return res.status(404).json({ error: "Coleção não encontrada." }); db.prepare("INSERT OR IGNORE INTO collection_items(collection_id,property_id,comment) VALUES(?,?,?)").run(c.id, req.body.property_id, req.body.comment || ""); res.json({ ok: true }) });
app.delete("/api/me/collections/:id/items/:propertyId", auth, (req, res) => { db.prepare("DELETE FROM collection_items WHERE collection_id=? AND property_id=?").run(req.params.id, req.params.propertyId); res.json({ ok: true }) });
app.get("/api/me/saved-searches", auth, (req, res) => res.json(db.prepare("SELECT * FROM saved_searches WHERE user_id=? ORDER BY created_at DESC").all(req.session.user.id)));
app.post("/api/me/saved-searches", auth, (req, res) => { const r = db.prepare("INSERT INTO saved_searches(user_id,name,filters_json,frequency) VALUES(?,?,?,?)").run(req.session.user.id, req.body.name || "Minha busca", JSON.stringify(req.body.filters || {}), req.body.frequency || "instant"); res.status(201).json({ id: r.lastInsertRowid }) });
app.delete("/api/me/saved-searches/:id", auth, (req, res) => { db.prepare("DELETE FROM saved_searches WHERE id=? AND user_id=?").run(req.params.id, req.session.user.id); res.json({ ok: true }) });
app.get("/api/me/notifications", auth, (req, res) => res.json(db.prepare("SELECT * FROM notifications WHERE user_id=? ORDER BY created_at DESC LIMIT 50").all(req.session.user.id)));
app.patch("/api/me/notifications/:id/read", auth, (req, res) => { db.prepare("UPDATE notifications SET read_at=CURRENT_TIMESTAMP WHERE id=? AND user_id=?").run(req.params.id, req.session.user.id); res.json({ ok: true }) });

app.get("/api/owner/properties", auth, (req, res) => { if (req.session.user.role !== "owner") return res.status(403).json({ error: "Acesso negado." }); res.json(db.prepare("SELECT * FROM properties WHERE owner_id=? ORDER BY updated_at DESC").all(req.session.user.id).map(normalize)) });
app.post("/api/owner/properties", auth, (req, res) => { if (req.session.user.role !== "owner") return res.status(403).json({ error: "Acesso negado." }); const b = req.body || {}; if (!b.title || !b.type || !b.purpose || !b.city || !b.neighborhood) return res.status(400).json({ error: "Preencha título, tipo, finalidade, cidade e bairro." }); const vals = propertyPayload(b); const r = db.prepare("INSERT INTO properties(owner_id,title,type,purpose,price,city,neighborhood,address,area,bedrooms,suites,bathrooms,parking,condo,iptu,description,features,video_url,latitude,longitude,status) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(req.session.user.id, ...vals, "pending"); notify(req.session.user.id, "Anúncio enviado", "Seu imóvel está aguardando análise.", "property"); res.status(201).json(normalize(db.prepare("SELECT * FROM properties WHERE id=?").get(r.lastInsertRowid))) });
app.patch("/api/owner/properties/:id", auth, (req, res) => { if (req.session.user.role !== "owner") return res.status(403).json({ error: "Acesso negado." }); const p = db.prepare("SELECT * FROM properties WHERE id=?").get(req.params.id); if (!p) return res.status(404).json({ error: "Imóvel não encontrado." }); if (p.owner_id !== req.session.user.id) return res.status(403).json({ error: "Você só pode editar seus próprios anúncios." }); const v = propertyPayload(req.body, p); db.prepare("UPDATE properties SET title=?,type=?,purpose=?,price=?,city=?,neighborhood=?,address=?,area=?,bedrooms=?,suites=?,bathrooms=?,parking=?,condo=?,iptu=?,description=?,features=?,video_url=?,latitude=?,longitude=?,status='pending',updated_at=CURRENT_TIMESTAMP WHERE id=?").run(...v, p.id); notify(req.session.user.id, "Alteração enviada", "Seu anúncio voltou para análise.", "property"); res.json(normalize(db.prepare("SELECT * FROM properties WHERE id=?").get(p.id))) });

app.post("/api/owner/properties/:id/images", auth, upload.array("images", 20), (req, res) => { if (req.session.user.role !== "owner") return res.status(403).json({ error: "Acesso negado." }); const propertyId = Number(req.params.id); const prop = db.prepare("SELECT id,owner_id FROM properties WHERE id=?").get(propertyId); if (!prop) return res.status(404).json({ error: "Imóvel não encontrado." }); if (prop.owner_id !== req.session.user.id) return res.status(403).json({ error: "Você só pode adicionar imagens aos seus próprios anúncios." }); const files = req.files || []; if (!files.length) return res.status(400).json({ error: "Selecione pelo menos uma imagem." }); let max = db.prepare("SELECT COALESCE(MAX(sort_order),0) m FROM property_images WHERE property_id=?").get(propertyId).m; const st = db.prepare("INSERT INTO property_images(property_id,filename,sort_order) VALUES(?,?,?)"); db.transaction(fsx => fsx.forEach((f, i) => st.run(propertyId, f.filename, max + i + 1)))(files); if (!prop.cover_image) db.prepare("UPDATE properties SET cover_image=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(files[0].filename, propertyId); notify(req.session.user.id, "Fotos adicionadas", "As novas imagens foram anexadas ao seu anúncio.", "property"); res.json(normalize(db.prepare("SELECT * FROM properties WHERE id=?").get(propertyId))) });

app.get("/api/agent/summary", agentOnly, (req, res) => { const id = req.session.user.id; const leads = db.prepare("SELECT COUNT(*) c FROM leads WHERE assigned_to=?").get(id).c; const openLeads = db.prepare("SELECT COUNT(*) c FROM leads WHERE assigned_to=? AND status NOT IN ('closed','lost')").get(id).c; const tasks = db.prepare("SELECT COUNT(*) c FROM tasks WHERE user_id=? AND status='open'").get(id).c; const unread = db.prepare("SELECT COUNT(*) c FROM messages WHERE recipient_id=? AND read_at IS NULL").get(id).c; res.json({ leads, openLeads, tasks, unread }) });
app.get("/api/agent/leads", agentOnly, (req, res) => res.json(db.prepare("SELECT l.*,p.title property_title FROM leads l LEFT JOIN properties p ON p.id=l.property_id WHERE l.assigned_to=? ORDER BY l.updated_at DESC LIMIT 100").all(req.session.user.id)));
app.get("/api/agent/tasks", agentOnly, (req, res) => res.json(db.prepare("SELECT t.*,l.name lead_name,p.title property_title FROM tasks t LEFT JOIN leads l ON l.id=t.lead_id LEFT JOIN properties p ON p.id=t.property_id WHERE t.user_id=? ORDER BY CASE WHEN t.status='open' THEN 0 ELSE 1 END,t.due_at LIMIT 100").all(req.session.user.id)));
app.patch("/api/agent/tasks/:id", agentOnly, (req, res) => { const task = db.prepare("SELECT id FROM tasks WHERE id=? AND user_id=?").get(req.params.id, req.session.user.id); if (!task) return res.status(404).json({ error: "Tarefa não encontrada." }); db.prepare("UPDATE tasks SET status=? WHERE id=?").run(req.body.status || "done", task.id); res.json({ ok: true }) });
app.get("/api/admin/stats", staff, (req, res) => res.json({ properties: db.prepare("SELECT COUNT(*) c FROM properties").get().c, published: db.prepare("SELECT COUNT(*) c FROM properties WHERE status='published'").get().c, leads: db.prepare("SELECT COUNT(*) c FROM leads").get().c, newLeads: db.prepare("SELECT COUNT(*) c FROM leads WHERE status='new'").get().c, visits: db.prepare("SELECT COUNT(*) c FROM visits WHERE status='scheduled'").get().c, owners: db.prepare("SELECT COUNT(*) c FROM users WHERE role='owner'").get().c, customers: db.prepare("SELECT COUNT(*) c FROM users WHERE role='customer'").get().c, agents: db.prepare("SELECT COUNT(*) c FROM users WHERE role='agent'").get().c }));
app.get("/api/admin/users", manage, (req, res) => res.json(db.prepare("SELECT id,name,email,role,phone,created_at FROM users ORDER BY name").all()));
app.post("/api/admin/users", manage, (req, res) => { const { name, email, password, role = "owner", phone = "" } = req.body || {}; if (!name || !email || !password) return res.status(400).json({ error: "Nome, e-mail e senha são obrigatórios." }); if (!roles.admin.includes(role)) return res.status(400).json({ error: "Perfil inválido." }); try { const r = db.prepare("INSERT INTO users(name,email,password_hash,role,phone) VALUES(?,?,?,?,?)").run(name, email.toLowerCase(), bcrypt.hashSync(password, 12), role, phone); res.status(201).json({ id: r.lastInsertRowid }) } catch (e) { res.status(409).json({ error: "E-mail já cadastrado." }) } });
app.patch("/api/admin/users/:id", manage, (req, res) => { const u = db.prepare("SELECT * FROM users WHERE id=?").get(req.params.id); if (!u) return res.status(404).json({ error: "Usuário não encontrado." }); if (req.body.role && !roles.admin.includes(req.body.role)) return res.status(400).json({ error: "Perfil inválido." }); db.prepare("UPDATE users SET name=?,phone=?,role=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(req.body.name ?? u.name, req.body.phone ?? u.phone, req.body.role ?? u.role, u.id); res.json({ ok: true }) });
app.get("/api/admin/leads", staff, (req, res) => res.json(db.prepare("SELECT l.*,p.title property_title,u.name assigned_name FROM leads l LEFT JOIN properties p ON p.id=l.property_id LEFT JOIN users u ON u.id=l.assigned_to ORDER BY l.created_at DESC").all()));
app.patch("/api/admin/leads/:id", staff, (req, res) => { const allowed = ["new", "contacted", "qualified", "visit", "proposal", "negotiation", "closed", "lost"]; if (!allowed.includes(req.body.status)) return res.status(400).json({ error: "Status inválido." }); db.prepare("UPDATE leads SET status=?,assigned_to=COALESCE(?,assigned_to),updated_at=CURRENT_TIMESTAMP WHERE id=?").run(req.body.status, req.body.assigned_to || null, req.params.id); res.json({ ok: true }) });
app.get("/api/admin/properties", staff, (req, res) => res.json(db.prepare("SELECT p.*,u.name owner_name FROM properties p LEFT JOIN users u ON u.id=p.owner_id ORDER BY p.updated_at DESC").all().map(normalize)));
app.post("/api/admin/properties", manage, (req, res) => { const b = req.body || {}; if (!b.title || !b.type || !b.purpose || !b.city || !b.neighborhood) return res.status(400).json({ error: "Campos obrigatórios ausentes." }); const vals = propertyPayload(b); const r = db.prepare("INSERT INTO properties(owner_id,title,type,purpose,price,city,neighborhood,address,area,bedrooms,suites,bathrooms,parking,condo,iptu,description,features,video_url,latitude,longitude,status,cover_image) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(b.owner_id || req.session.user.id, ...vals, b.status || "draft", b.cover_image || null); log(req, "create", "property", r.lastInsertRowid); res.status(201).json(normalize(db.prepare("SELECT * FROM properties WHERE id=?").get(r.lastInsertRowid))) });
app.patch("/api/admin/properties/:id", manage, (req, res) => { const p = db.prepare("SELECT * FROM properties WHERE id=?").get(req.params.id); if (!p) return res.status(404).json({ error: "Imóvel não encontrado." }); const v = propertyPayload(req.body, p); db.prepare("UPDATE properties SET title=?,type=?,purpose=?,price=?,city=?,neighborhood=?,address=?,area=?,bedrooms=?,suites=?,bathrooms=?,parking=?,condo=?,iptu=?,description=?,features=?,video_url=?,latitude=?,longitude=?,cover_image=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(...v, req.body.cover_image ?? p.cover_image, p.id); log(req, "update", "property", p.id); res.json(normalize(db.prepare("SELECT * FROM properties WHERE id=?").get(p.id))) });
app.patch("/api/admin/properties/:id/status", manage, (req, res) => { const allowed = ["draft", "pending", "published", "paused", "sold", "rented", "archived"]; if (!allowed.includes(req.body.status)) return res.status(400).json({ error: "Status inválido." }); const p = db.prepare("SELECT * FROM properties WHERE id=?").get(req.params.id); db.prepare("UPDATE properties SET status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(req.body.status, req.params.id); if (p?.owner_id) notify(p.owner_id, "Status do anúncio atualizado", `Seu imóvel agora está com status: ${req.body.status}.`, "property"); log(req, "status", "property", req.params.id, req.body.status); res.json({ ok: true }) });
app.post("/api/admin/properties/:id/images", manage, upload.array("images", 20), (req, res) => { const p = db.prepare("SELECT id FROM properties WHERE id=?").get(req.params.id); if (!p) return res.status(404).json({ error: "Imóvel não encontrado." }); let max = db.prepare("SELECT COALESCE(MAX(sort_order),0) m FROM property_images WHERE property_id=?").get(p.id).m; const st = db.prepare("INSERT INTO property_images(property_id,filename,sort_order) VALUES(?,?,?)"); db.transaction(fsx => fsx.forEach((f, i) => st.run(p.id, f.filename, max + i + 1)))(req.files || []); if (req.files?.[0] && !db.prepare("SELECT cover_image FROM properties WHERE id=?").get(p.id).cover_image) db.prepare("UPDATE properties SET cover_image=? WHERE id=?").run(req.files[0].filename, p.id); res.json(normalize(db.prepare("SELECT * FROM properties WHERE id=?").get(p.id))) });
app.post("/api/visits", auth, (req, res) => { const b = req.body || {}; if (!b.property_id || !b.visit_date) return res.status(400).json({ error: "Imóvel e data da visita são obrigatórios." }); const p = db.prepare("SELECT id,title FROM properties WHERE id=? AND status='published'").get(b.property_id); if (!p) return res.status(404).json({ error: "Imóvel não encontrado." }); const customerId = req.session.user.role === "customer" ? req.session.user.id : null; const r = db.prepare("INSERT INTO visits(property_id,customer_id,agent_id,visit_date,notes) VALUES(?,?,?,?,?)").run(p.id, customerId, null, b.visit_date, b.notes || ""); res.status(201).json({ id: r.lastInsertRowid, message: "Visita solicitada." }) });
app.get("/api/admin/visits", staff, (req, res) => res.json(db.prepare("SELECT v.*,l.name lead_name,p.title property_title,u.name agent_name FROM visits v LEFT JOIN leads l ON l.id=v.lead_id LEFT JOIN properties p ON p.id=v.property_id LEFT JOIN users u ON u.id=v.agent_id ORDER BY v.visit_date ASC").all()));
app.post("/api/admin/visits", staff, (req, res) => { const b = req.body || {}; if (!b.visit_date) return res.status(400).json({ error: "Data da visita é obrigatória." }); const r = db.prepare("INSERT INTO visits(lead_id,property_id,customer_id,agent_id,visit_date,notes) VALUES(?,?,?,?,?,?)").run(b.lead_id || null, b.property_id || null, b.customer_id || null, b.agent_id || req.session.user.id, b.visit_date, b.notes || ""); if (b.customer_id) notify(b.customer_id, "Visita agendada", "Sua visita foi registrada no Imob Pro.", "visit"); res.status(201).json({ id: r.lastInsertRowid }) });
app.get("/api/admin/tasks", staff, (req, res) => res.json(db.prepare("SELECT t.*,u.name user_name,l.name lead_name,p.title property_title FROM tasks t LEFT JOIN users u ON u.id=t.user_id LEFT JOIN leads l ON l.id=t.lead_id LEFT JOIN properties p ON p.id=t.property_id ORDER BY CASE WHEN t.status='open' THEN 0 ELSE 1 END,t.due_at").all()));
app.post("/api/admin/tasks", staff, (req, res) => { if (!req.body.title) return res.status(400).json({ error: "Título obrigatório." }); const r = db.prepare("INSERT INTO tasks(user_id,lead_id,property_id,title,due_at,priority,notes) VALUES(?,?,?,?,?,?,?)").run(req.body.user_id || req.session.user.id, req.body.lead_id || null, req.body.property_id || null, req.body.title, req.body.due_at || null, req.body.priority || "normal", req.body.notes || ""); res.status(201).json({ id: r.lastInsertRowid }) });
app.patch("/api/admin/tasks/:id", staff, (req, res) => { db.prepare("UPDATE tasks SET status=? WHERE id=?").run(req.body.status || "done", req.params.id); res.json({ ok: true }) });
app.patch("/api/admin/settings", manage, (req, res) => { const st = db.prepare("INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value"); db.transaction(o => Object.entries(o || {}).forEach(([k, v]) => st.run(k, String(v))))(req.body); res.json(getSettings()) });
app.get("/api/admin/activity", staff, (req, res) => res.json(db.prepare("SELECT a.*,u.name user_name FROM activity_log a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.created_at DESC LIMIT 100").all()));

app.post("/api/properties/:id/view", (req, res) => { const p = db.prepare("SELECT id,status FROM properties WHERE id=?").get(req.params.id); if (!p || p.status !== "published") return res.status(404).json({ error: "Imóvel não encontrado." }); const sessionKey = req.sessionID; db.prepare("INSERT INTO property_views(property_id,user_id,session_key,source) VALUES(?,?,?,?)").run(p.id, req.session.user?.id || null, sessionKey, req.body.source || "direct"); res.json({ ok: true }) });
app.get("/api/admin/property-analytics/:id", staff, (req, res) => { const p = db.prepare("SELECT id,title FROM properties WHERE id=?").get(req.params.id); if (!p) return res.status(404).json({ error: "Imóvel não encontrado." }); const total = db.prepare("SELECT COUNT(*) c FROM property_views WHERE property_id=?").get(p.id).c; const unique = db.prepare("SELECT COUNT(DISTINCT session_key) c FROM property_views WHERE property_id=?").get(p.id).c; const favorites = db.prepare("SELECT COUNT(*) c FROM favorites WHERE property_id=?").get(p.id).c; const leads = db.prepare("SELECT COUNT(*) c FROM leads WHERE property_id=?").get(p.id).c; const visits = db.prepare("SELECT COUNT(*) c FROM visits WHERE property_id=?").get(p.id).c; res.json({ property: p, total, unique, favorites, leads, visits }) });
app.get("/api/admin/messages", staff, (req, res) => res.json(db.prepare("SELECT m.*,s.name sender_name,r.name recipient_name,p.title property_title FROM messages m LEFT JOIN users s ON s.id=m.sender_id LEFT JOIN users r ON r.id=m.recipient_id LEFT JOIN properties p ON p.id=m.property_id ORDER BY m.created_at DESC LIMIT 200").all()));
app.get("/api/messages/contacts", auth, (req, res) => {
  const r = req.session.user.role;
  if (["admin", "manager", "editor", "agent"].includes(r)) {
    return res.json(db.prepare("SELECT id,name,email,role,phone FROM users WHERE id<>? AND role IN ('customer','owner','agent','manager','admin') ORDER BY name LIMIT 200").all(req.session.user.id));
  }
  const contacts = db.prepare("SELECT id,name,email,role,phone FROM users WHERE role IN ('admin','manager','agent') ORDER BY CASE role WHEN 'admin' THEN 0 WHEN 'manager' THEN 1 ELSE 2 END,name LIMIT 20").all();
  res.json(contacts);
});
app.get("/api/messages", auth, (req, res) => {
  const uid = req.session.user.id, other = Number(req.query.with || 0);
  let sql = "SELECT m.*,s.name sender_name,r.name recipient_name,p.title property_title FROM messages m LEFT JOIN users s ON s.id=m.sender_id LEFT JOIN users r ON r.id=m.recipient_id LEFT JOIN properties p ON p.id=m.property_id WHERE (m.sender_id=? AND m.recipient_id=?) OR (m.sender_id=? AND m.recipient_id=?) ORDER BY m.created_at ASC LIMIT 200";
  if (!other) return res.json([]);
  const rows = db.prepare(sql).all(uid, other, other, uid);
  db.prepare("UPDATE messages SET read_at=CURRENT_TIMESTAMP WHERE recipient_id=? AND sender_id=? AND read_at IS NULL").run(uid, other);
  res.json(rows);
});
app.get("/api/messages/unread", auth, (req, res) => res.json({ count: db.prepare("SELECT COUNT(*) c FROM messages WHERE recipient_id=? AND read_at IS NULL").get(req.session.user.id).c }));
app.post("/api/messages", auth, (req, res) => { if (!req.body.recipient_id || !req.body.body) return res.status(400).json({ error: "Destinatário e mensagem são obrigatórios." }); const recipient = db.prepare("SELECT id FROM users WHERE id=?").get(req.body.recipient_id); if (!recipient) return res.status(404).json({ error: "Destinatário não encontrado." }); const body = String(req.body.body).trim(); if (body.length > 2000) return res.status(400).json({ error: "A mensagem pode ter no máximo 2.000 caracteres." }); const r = db.prepare("INSERT INTO messages(sender_id,recipient_id,property_id,lead_id,body) VALUES(?,?,?,?,?)").run(req.session.user.id, req.body.recipient_id, req.body.property_id || null, req.body.lead_id || null, body); notify(req.body.recipient_id, "Nova mensagem", `Você recebeu uma nova mensagem de ${req.session.user.name}.`, "message"); log(req, "send", "message", r.lastInsertRowid); res.status(201).json({ id: r.lastInsertRowid, created_at: new Date().toISOString() }) });

// Perfil e direitos do titular (LGPD): a aplicação oferece consulta, exportação e abertura de solicitação.
app.get("/api/me/profile", auth, (req, res) => { const u = db.prepare("SELECT id,name,email,phone,role,created_at FROM users WHERE id=?").get(req.session.user.id); res.json(u) });
app.patch("/api/me/profile", auth, (req, res) => { const name = String(req.body.name || "").trim(), phone = String(req.body.phone || "").trim(); if (!name) return res.status(400).json({ error: "Nome obrigatório." }); db.prepare("UPDATE users SET name=?,phone=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(name, phone, req.session.user.id); const u = db.prepare("SELECT * FROM users WHERE id=?").get(req.session.user.id); req.session.user = publicUser(u); res.json(req.session.user) });
app.get("/api/me/export", auth, (req, res) => { const uid = req.session.user.id; const u = db.prepare("SELECT id,name,email,phone,role,created_at FROM users WHERE id=?").get(uid); const favorites = db.prepare("SELECT property_id,created_at FROM favorites WHERE user_id=?").all(uid); const searches = db.prepare("SELECT id,name,filters_json,frequency,created_at FROM saved_searches WHERE user_id=?").all(uid); const collections = db.prepare("SELECT * FROM collections WHERE user_id=?").all(uid); res.json({ user: u, favorites, saved_searches: searches, collections }) });
app.post("/api/me/privacy-requests", auth, (req, res) => { const type = String(req.body.type || "access"); const allowed = ["access", "correction", "deletion", "portability", "revocation", "information"]; if (!allowed.includes(type)) return res.status(400).json({ error: "Tipo de solicitação inválido." }); const r = db.prepare("INSERT INTO privacy_requests(user_id,type,details) VALUES(?,?,?)").run(req.session.user.id, type, String(req.body.details || "")); notify(req.session.user.id, "Solicitação registrada", "Sua solicitação de privacidade foi registrada para análise.", "privacy"); res.status(201).json({ id: r.lastInsertRowid }) });
app.get("/api/admin/privacy-requests", manage, (req, res) => res.json(db.prepare("SELECT pr.*,u.name user_name,u.email FROM privacy_requests pr JOIN users u ON u.id=pr.user_id ORDER BY pr.created_at DESC").all()));
app.get("/api/admin/automations", manage, (req, res) => res.json(db.prepare("SELECT * FROM automation_rules ORDER BY id").all()));
app.post("/api/admin/automations", manage, (req, res) => { const { name, trigger_key, action_key } = req.body || {}; if (!name || !trigger_key || !action_key) return res.status(400).json({ error: "Preencha nome, gatilho e ação." }); const r = db.prepare("INSERT INTO automation_rules(name,trigger_key,action_key) VALUES(?,?,?)").run(name, trigger_key, action_key); res.status(201).json({ id: r.lastInsertRowid }) });
app.patch("/api/admin/automations/:id", manage, (req, res) => { db.prepare("UPDATE automation_rules SET enabled=? WHERE id=?").run(req.body.enabled ? 1 : 0, req.params.id); res.json({ ok: true }) });
app.get(/.*/, (req, res) => { if (req.path.startsWith("/api/")) return res.status(404).json({ error: "Rota não encontrada." }); res.sendFile(path.join(__dirname, "public", "index.html")) });
app.use((err, req, res, next) => {
  if (err instanceof multer.MulterError || err?.message === "Apenas JPG, PNG ou WEBP.") return res.status(400).json({ error: err.code === "LIMIT_FILE_SIZE" ? "Cada imagem pode ter no máximo 10 MB." : err.message });
  console.error(err);
  if (res.headersSent) return next(err);
  res.status(500).json({ error: isProd ? "Erro interno do servidor." : (err.message || "Erro interno do servidor.") });
});

app.listen(PORT, () => console.log(`Imob Pro rodando na porta ${PORT}`));
